# Generated by Django 4.1.5 on 2023-01-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_question_id_question_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='uuid',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
